---
# BACKUP CISCO SWITCH by João Vitor Costa Medeiros
# Task to create a directory "Switches" with the path "C:/bkp_year-month-day/Switches/" (Feel free to edit)
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Collect Year, Month and Day.
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"
    
    - name: Put today's date in a variable.
      set_fact:
        DTG: "{{ ansible_date_time.date }}"

    - name: Create directory with the following path C:\bkp_"year-month-day"\Switches\
      file:
        path: /mnt/c/bkp_{{ hostvars.localhost.DTG }}/Switches/
        state: directory
  run_once: true

# Task to backup Cisco Switch Config File and save it in the path "/bkp_year-month-day/Switch/hostname.cfg"
# Remember to change or maintain the same path in both tasks.

- hosts: switches_cisco
  gather_facts: false

  tasks:
    - name: Copy the configuration file of each CISCO 2960 Switch and put it in a .cfg file
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: /mnt/c/bkp_{{ hostvars.localhost.DTG }}/Switches/
